//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ddupe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ddupe.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache is empty as of yet....
        /// </summary>
        internal static string IDS_cache_is_empty {
            get {
                return ResourceManager.GetString("IDS_cache_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0} hashes from the cache in {1}....
        /// </summary>
        internal static string IDS_cache_read {
            get {
                return ResourceManager.GetString("IDS_cache_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache file name.
        /// </summary>
        internal static string IDS_CMD_cache_doc {
            get {
                return ResourceManager.GetString("IDS_CMD_cache_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete files (default: list only).
        /// </summary>
        internal static string IDS_CMD_delete_doc {
            get {
                return ResourceManager.GetString("IDS_CMD_delete_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one or more directories to search.
        /// </summary>
        internal static string IDS_CMD_dir_doc {
            get {
                return ResourceManager.GetString("IDS_CMD_dir_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum size for files.
        /// </summary>
        internal static string IDS_CMD_minsize_doc {
            get {
                return ResourceManager.GetString("IDS_CMD_minsize_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search directories recursively.
        /// </summary>
        internal static string IDS_CMD_recursive_doc {
            get {
                return ResourceManager.GetString("IDS_CMD_recursive_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename files in MD5 format.
        /// </summary>
        internal static string IDS_CMD_rename_doc {
            get {
                return ResourceManager.GetString("IDS_CMD_rename_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeware written by Gerson Kurz (http://p-nand-q.com).
        /// </summary>
        internal static string IDS_COPYRIGHT {
            get {
                return ResourceManager.GetString("IDS_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists as {1} [{2} bytes].
        /// </summary>
        internal static string IDS_dupe_found {
            get {
                return ResourceManager.GetString("IDS_dupe_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR, unable to read database &apos;{0}&apos;.
        /// </summary>
        internal static string IDS_ERR_db_read {
            get {
                return ResourceManager.GetString("IDS_ERR_db_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR, {0} doesn&apos;t exist....
        /// </summary>
        internal static string IDS_ERR_does_not_exist {
            get {
                return ResourceManager.GetString("IDS_ERR_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR, unable to execute statement &apos;{0}&apos;.
        /// </summary>
        internal static string IDS_ERR_execute_statement {
            get {
                return ResourceManager.GetString("IDS_ERR_execute_statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR, unable to read directory &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string IDS_ERR_unable_to_read {
            get {
                return ResourceManager.GetString("IDS_ERR_unable_to_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename {0} as {1}.
        /// </summary>
        internal static string IDS_ERR_unable_to_rename {
            get {
                return ResourceManager.GetString("IDS_ERR_unable_to_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddupe finished after {0}.
        /// </summary>
        internal static string IDS_finished {
            get {
                return ResourceManager.GetString("IDS_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to read cache from &quot;{0}&quot;.
        /// </summary>
        internal static string IDS_reading_cache {
            get {
                return ResourceManager.GetString("IDS_reading_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bytes.
        /// </summary>
        internal static string IDS_size_bytes {
            get {
                return ResourceManager.GetString("IDS_size_bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} GB.
        /// </summary>
        internal static string IDS_size_GB {
            get {
                return ResourceManager.GetString("IDS_size_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        internal static string IDS_size_KB {
            get {
                return ResourceManager.GetString("IDS_size_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} MB.
        /// </summary>
        internal static string IDS_size_MB {
            get {
                return ResourceManager.GetString("IDS_size_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string IDS_TITLE {
            get {
                return ResourceManager.GetString("IDS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked a total of {0} files using {1}, calculating {2} hashes in {3} ticks..
        /// </summary>
        internal static string IDS_total_checked {
            get {
                return ResourceManager.GetString("IDS_total_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of these, {0} files [{2:0.00%}] using {1} [{3:0.00%}] were duplicates..
        /// </summary>
        internal static string IDS_total_dupes {
            get {
                return ResourceManager.GetString("IDS_total_dupes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hashes from {0} filenames using {1}.
        /// </summary>
        internal static string IDS_total_hashes {
            get {
                return ResourceManager.GetString("IDS_total_hashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed a total of {0} files using {1}.
        /// </summary>
        internal static string IDS_total_renamed {
            get {
                return ResourceManager.GetString("IDS_total_renamed", resourceCulture);
            }
        }
    }
}
