//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace md5sums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("md5sums.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string IDS_check {
            get {
                return ResourceManager.GetString("IDS_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one or more directories to search.
        /// </summary>
        internal static string IDS_CMD_dir_doc {
            get {
                return ResourceManager.GetString("IDS_CMD_dir_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search directories recursively.
        /// </summary>
        internal static string IDS_CMD_recursive_doc {
            get {
                return ResourceManager.GetString("IDS_CMD_recursive_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeware written by Gerson Kurz (http://p-nand-q.com).
        /// </summary>
        internal static string IDS_COPYRIGHT {
            get {
                return ResourceManager.GetString("IDS_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR, {0} doesn&apos;t exist....
        /// </summary>
        internal static string IDS_ERR_does_not_exist {
            get {
                return ResourceManager.GetString("IDS_ERR_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR, unable to read directory &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string IDS_ERR_unable_to_read {
            get {
                return ResourceManager.GetString("IDS_ERR_unable_to_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string IDS_TITLE {
            get {
                return ResourceManager.GetString("IDS_TITLE", resourceCulture);
            }
        }
    }
}
