//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pserv4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pserv4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue the selected device(s).
        /// </summary>
        internal static string DEVICES_CTRL_CONTINUE_Description {
            get {
                return ResourceManager.GetString("DEVICES_CTRL_CONTINUE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause the selected device(s).
        /// </summary>
        internal static string DEVICES_CTRL_PAUSE_Description {
            get {
                return ResourceManager.GetString("DEVICES_CTRL_PAUSE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the selected device(s).
        /// </summary>
        internal static string DEVICES_CTRL_RESTART_Description {
            get {
                return ResourceManager.GetString("DEVICES_CTRL_RESTART_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the selected device(s).
        /// </summary>
        internal static string DEVICES_CTRL_START_Description {
            get {
                return ResourceManager.GetString("DEVICES_CTRL_START_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the selected device(s).
        /// </summary>
        internal static string DEVICES_CTRL_STOP_Description {
            get {
                return ResourceManager.GetString("DEVICES_CTRL_STOP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string IDS_CONFIRMATION {
            get {
                return ResourceManager.GetString("IDS_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string IDS_PROPERTIES {
            get {
                return ResourceManager.GetString("IDS_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this product: {0}?.
        /// </summary>
        internal static string IDS_UNINSTALLER_SureToRemoveKey {
            get {
                return ResourceManager.GetString("IDS_UNINSTALLER_SureToRemoveKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Description.
        /// </summary>
        internal static string MODULE_C_FileDescription {
            get {
                return ResourceManager.GetString("MODULE_C_FileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        internal static string MODULE_C_FileVersion {
            get {
                return ResourceManager.GetString("MODULE_C_FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Size.
        /// </summary>
        internal static string MODULE_C_ModuleMemorySize {
            get {
                return ResourceManager.GetString("MODULE_C_ModuleMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MODULE_C_Name {
            get {
                return ResourceManager.GetString("MODULE_C_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string MODULE_C_Path {
            get {
                return ResourceManager.GetString("MODULE_C_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        internal static string MODULE_C_ProcessID {
            get {
                return ResourceManager.GetString("MODULE_C_ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string MODULE_C_Product {
            get {
                return ResourceManager.GetString("MODULE_C_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Version.
        /// </summary>
        internal static string MODULE_C_ProductVersion {
            get {
                return ResourceManager.GetString("MODULE_C_ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Description.
        /// </summary>
        internal static string PROCESS_C_FileDescription {
            get {
                return ResourceManager.GetString("PROCESS_C_FileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        internal static string PROCESS_C_FileVersion {
            get {
                return ResourceManager.GetString("PROCESS_C_FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Count.
        /// </summary>
        internal static string PROCESS_C_HandleCount {
            get {
                return ResourceManager.GetString("PROCESS_C_HandleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        internal static string PROCESS_C_ID {
            get {
                return ResourceManager.GetString("PROCESS_C_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Window Handle.
        /// </summary>
        internal static string PROCESS_C_MainWindowHandle {
            get {
                return ResourceManager.GetString("PROCESS_C_MainWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Window Title.
        /// </summary>
        internal static string PROCESS_C_MainWindowTitle {
            get {
                return ResourceManager.GetString("PROCESS_C_MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PROCESS_C_Name {
            get {
                return ResourceManager.GetString("PROCESS_C_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonpaged System Memory.
        /// </summary>
        internal static string PROCESS_C_NonpagedSystemMemorySize64 {
            get {
                return ResourceManager.GetString("PROCESS_C_NonpagedSystemMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paged Memory.
        /// </summary>
        internal static string PROCESS_C_PagedMemorySize64 {
            get {
                return ResourceManager.GetString("PROCESS_C_PagedMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paged System Memory.
        /// </summary>
        internal static string PROCESS_C_PagedSystemMemorySize64 {
            get {
                return ResourceManager.GetString("PROCESS_C_PagedSystemMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PROCESS_C_Path {
            get {
                return ResourceManager.GetString("PROCESS_C_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Paged Memory.
        /// </summary>
        internal static string PROCESS_C_PeakPagedMemorySize64 {
            get {
                return ResourceManager.GetString("PROCESS_C_PeakPagedMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Virtual Memory.
        /// </summary>
        internal static string PROCESS_C_PeakVirtualMemorySize64 {
            get {
                return ResourceManager.GetString("PROCESS_C_PeakVirtualMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Working Set.
        /// </summary>
        internal static string PROCESS_C_PeakWorkingSet64 {
            get {
                return ResourceManager.GetString("PROCESS_C_PeakWorkingSet64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Memory.
        /// </summary>
        internal static string PROCESS_C_PrivateMemorySize64 {
            get {
                return ResourceManager.GetString("PROCESS_C_PrivateMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privileged Processor Time.
        /// </summary>
        internal static string PROCESS_C_PrivilegedProcessorTime {
            get {
                return ResourceManager.GetString("PROCESS_C_PrivilegedProcessorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Priority Class.
        /// </summary>
        internal static string PROCESS_C_ProcessPriorityClass {
            get {
                return ResourceManager.GetString("PROCESS_C_ProcessPriorityClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string PROCESS_C_Product {
            get {
                return ResourceManager.GetString("PROCESS_C_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Version.
        /// </summary>
        internal static string PROCESS_C_ProductVersion {
            get {
                return ResourceManager.GetString("PROCESS_C_ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reponding.
        /// </summary>
        internal static string PROCESS_C_Responding {
            get {
                return ResourceManager.GetString("PROCESS_C_Responding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID.
        /// </summary>
        internal static string PROCESS_C_SessionId {
            get {
                return ResourceManager.GetString("PROCESS_C_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Info Arguments.
        /// </summary>
        internal static string PROCESS_C_StartInfoArguments {
            get {
                return ResourceManager.GetString("PROCESS_C_StartInfoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string PROCESS_C_StartTime {
            get {
                return ResourceManager.GetString("PROCESS_C_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Count.
        /// </summary>
        internal static string PROCESS_C_ThreadCount {
            get {
                return ResourceManager.GetString("PROCESS_C_ThreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Processor Time.
        /// </summary>
        internal static string PROCESS_C_TotalProcessorTime {
            get {
                return ResourceManager.GetString("PROCESS_C_TotalProcessorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Run Time.
        /// </summary>
        internal static string PROCESS_C_TotalRunTime {
            get {
                return ResourceManager.GetString("PROCESS_C_TotalRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string PROCESS_C_User {
            get {
                return ResourceManager.GetString("PROCESS_C_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Memory.
        /// </summary>
        internal static string PROCESS_C_VirtualMemorySize64 {
            get {
                return ResourceManager.GetString("PROCESS_C_VirtualMemorySize64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Set.
        /// </summary>
        internal static string PROCESS_C_WorkingSet64 {
            get {
                return ResourceManager.GetString("PROCESS_C_WorkingSet64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause|Continue.
        /// </summary>
        internal static string SERVICE_ACCEPT_PAUSE_CONTINUE {
            get {
                return ResourceManager.GetString("SERVICE_ACCEPT_PAUSE_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string SERVICE_ACCEPT_STOP {
            get {
                return ResourceManager.GetString("SERVICE_ACCEPT_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string SERVICE_AUTO_START {
            get {
                return ResourceManager.GetString("SERVICE_AUTO_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot.
        /// </summary>
        internal static string SERVICE_BOOT_START {
            get {
                return ResourceManager.GetString("SERVICE_BOOT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Path Name.
        /// </summary>
        internal static string SERVICE_C_BinaryPathName {
            get {
                return ResourceManager.GetString("SERVICE_C_BinaryPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint.
        /// </summary>
        internal static string SERVICE_C_CheckPoint {
            get {
                return ResourceManager.GetString("SERVICE_C_CheckPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls Accepted.
        /// </summary>
        internal static string SERVICE_C_ControlsAccepted {
            get {
                return ResourceManager.GetString("SERVICE_C_ControlsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        internal static string SERVICE_C_CurrentState {
            get {
                return ResourceManager.GetString("SERVICE_C_CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SERVICE_C_Description {
            get {
                return ResourceManager.GetString("SERVICE_C_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string SERVICE_C_DisplayName {
            get {
                return ResourceManager.GetString("SERVICE_C_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Control.
        /// </summary>
        internal static string SERVICE_C_ErrorControl {
            get {
                return ResourceManager.GetString("SERVICE_C_ErrorControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Path.
        /// </summary>
        internal static string SERVICE_C_InstallLocation {
            get {
                return ResourceManager.GetString("SERVICE_C_InstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Order Group.
        /// </summary>
        internal static string SERVICE_C_LoadOrderGroup {
            get {
                return ResourceManager.GetString("SERVICE_C_LoadOrderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        internal static string SERVICE_C_ProcessID {
            get {
                return ResourceManager.GetString("SERVICE_C_ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Flags.
        /// </summary>
        internal static string SERVICE_C_ServiceFlags {
            get {
                return ResourceManager.GetString("SERVICE_C_ServiceFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string SERVICE_C_ServiceName {
            get {
                return ResourceManager.GetString("SERVICE_C_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service-Specific Exit Code.
        /// </summary>
        internal static string SERVICE_C_ServiceSpecificExitCode {
            get {
                return ResourceManager.GetString("SERVICE_C_ServiceSpecificExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        internal static string SERVICE_C_ServiceType {
            get {
                return ResourceManager.GetString("SERVICE_C_ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Type.
        /// </summary>
        internal static string SERVICE_C_StartType {
            get {
                return ResourceManager.GetString("SERVICE_C_StartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag ID.
        /// </summary>
        internal static string SERVICE_C_TagId {
            get {
                return ResourceManager.GetString("SERVICE_C_TagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SERVICE_C_User {
            get {
                return ResourceManager.GetString("SERVICE_C_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Hint.
        /// </summary>
        internal static string SERVICE_C_WaitHint {
            get {
                return ResourceManager.GetString("SERVICE_C_WaitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 Exit Code.
        /// </summary>
        internal static string SERVICE_C_Win32ExitCode {
            get {
                return ResourceManager.GetString("SERVICE_C_Win32ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Pending.
        /// </summary>
        internal static string SERVICE_CONTINUE_PENDING {
            get {
                return ResourceManager.GetString("SERVICE_CONTINUE_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string SERVICE_CONTROL_Continue {
            get {
                return ResourceManager.GetString("SERVICE_CONTROL_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string SERVICE_CONTROL_Pause {
            get {
                return ResourceManager.GetString("SERVICE_CONTROL_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string SERVICE_CONTROL_Restart {
            get {
                return ResourceManager.GetString("SERVICE_CONTROL_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string SERVICE_CONTROL_Start {
            get {
                return ResourceManager.GetString("SERVICE_CONTROL_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string SERVICE_CONTROL_Stop {
            get {
                return ResourceManager.GetString("SERVICE_CONTROL_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string SERVICE_DEMAND_START {
            get {
                return ResourceManager.GetString("SERVICE_DEMAND_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string SERVICE_DISABLED {
            get {
                return ResourceManager.GetString("SERVICE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string SERVICE_ERROR_CRITICAL {
            get {
                return ResourceManager.GetString("SERVICE_ERROR_CRITICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string SERVICE_ERROR_IGNORE {
            get {
                return ResourceManager.GetString("SERVICE_ERROR_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string SERVICE_ERROR_NORMAL {
            get {
                return ResourceManager.GetString("SERVICE_ERROR_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe.
        /// </summary>
        internal static string SERVICE_ERROR_SEVERE {
            get {
                return ResourceManager.GetString("SERVICE_ERROR_SEVERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        internal static string SERVICE_FILE_SYSTEM_DRIVER {
            get {
                return ResourceManager.GetString("SERVICE_FILE_SYSTEM_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive.
        /// </summary>
        internal static string SERVICE_INTERACTIVE_PROCESS {
            get {
                return ResourceManager.GetString("SERVICE_INTERACTIVE_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Driver.
        /// </summary>
        internal static string SERVICE_KERNEL_DRIVER {
            get {
                return ResourceManager.GetString("SERVICE_KERNEL_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Pending.
        /// </summary>
        internal static string SERVICE_PAUSE_PENDING {
            get {
                return ResourceManager.GetString("SERVICE_PAUSE_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string SERVICE_PAUSED {
            get {
                return ResourceManager.GetString("SERVICE_PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string SERVICE_RUNNING {
            get {
                return ResourceManager.GetString("SERVICE_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pending.
        /// </summary>
        internal static string SERVICE_START_PENDING {
            get {
                return ResourceManager.GetString("SERVICE_START_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Pending.
        /// </summary>
        internal static string SERVICE_STOP_PENDING {
            get {
                return ResourceManager.GetString("SERVICE_STOP_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string SERVICE_STOPPED {
            get {
                return ResourceManager.GetString("SERVICE_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SERVICE_SYSTEM_START {
            get {
                return ResourceManager.GetString("SERVICE_SYSTEM_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Process.
        /// </summary>
        internal static string SERVICE_WIN32_OWN_PROCESS {
            get {
                return ResourceManager.GetString("SERVICE_WIN32_OWN_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Process.
        /// </summary>
        internal static string SERVICE_WIN32_SHARE_PROCESS {
            get {
                return ResourceManager.GetString("SERVICE_WIN32_SHARE_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring up Explorer in installation path.
        /// </summary>
        internal static string SERVICES_BRING_UP_EXPLORER {
            get {
                return ResourceManager.GetString("SERVICES_BRING_UP_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring up Registry Editor for service key.
        /// </summary>
        internal static string SERVICES_BRING_UP_REGEDIT {
            get {
                return ResourceManager.GetString("SERVICES_BRING_UP_REGEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue the selected service(s).
        /// </summary>
        internal static string SERVICES_CTRL_CONTINUE_Description {
            get {
                return ResourceManager.GetString("SERVICES_CTRL_CONTINUE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause the selected service(s).
        /// </summary>
        internal static string SERVICES_CTRL_PAUSE_Description {
            get {
                return ResourceManager.GetString("SERVICES_CTRL_PAUSE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the selected service(s).
        /// </summary>
        internal static string SERVICES_CTRL_RESTART_Description {
            get {
                return ResourceManager.GetString("SERVICES_CTRL_RESTART_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the selected service(s).
        /// </summary>
        internal static string SERVICES_CTRL_START_Description {
            get {
                return ResourceManager.GetString("SERVICES_CTRL_START_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the selected service(s).
        /// </summary>
        internal static string SERVICES_CTRL_STOP_Description {
            get {
                return ResourceManager.GetString("SERVICES_CTRL_STOP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup: Automatic.
        /// </summary>
        internal static string SERVICES_SET_START_AUTOMATIC {
            get {
                return ResourceManager.GetString("SERVICES_SET_START_AUTOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup: Disabled.
        /// </summary>
        internal static string SERVICES_SET_START_DISABLED {
            get {
                return ResourceManager.GetString("SERVICES_SET_START_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup: Manual.
        /// </summary>
        internal static string SERVICES_SET_START_MANUAL {
            get {
                return ResourceManager.GetString("SERVICES_SET_START_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start CMD.EXE in installation path.
        /// </summary>
        internal static string SERVICES_START_CMD {
            get {
                return ResourceManager.GetString("SERVICES_START_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string SERVICES_UNINSTALL {
            get {
                return ResourceManager.GetString("SERVICES_UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring up Explorer in install location.
        /// </summary>
        internal static string UNINSTALLER_BRING_UP_EXPLORER {
            get {
                return ResourceManager.GetString("UNINSTALLER_BRING_UP_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring up Registry Editor for uninstall key.
        /// </summary>
        internal static string UNINSTALLER_BRING_UP_REGEDIT {
            get {
                return ResourceManager.GetString("UNINSTALLER_BRING_UP_REGEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string UNINSTALLER_C_AboutLink {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string UNINSTALLER_C_Action {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string UNINSTALLER_C_ApplicationName {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string UNINSTALLER_C_HelpLink {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Location.
        /// </summary>
        internal static string UNINSTALLER_C_InstallLocation {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_InstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string UNINSTALLER_C_Key {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string UNINSTALLER_C_ModifyPath {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_ModifyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string UNINSTALLER_C_Publisher {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string UNINSTALLER_C_Version {
            get {
                return ResourceManager.GetString("UNINSTALLER_C_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show about link.
        /// </summary>
        internal static string UNINSTALLER_CTRL_CONTINUE_Description {
            get {
                return ResourceManager.GetString("UNINSTALLER_CTRL_CONTINUE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help link.
        /// </summary>
        internal static string UNINSTALLER_CTRL_PAUSE_Description {
            get {
                return ResourceManager.GetString("UNINSTALLER_CTRL_PAUSE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring up registry editor.
        /// </summary>
        internal static string UNINSTALLER_CTRL_RESTART_Description {
            get {
                return ResourceManager.GetString("UNINSTALLER_CTRL_RESTART_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string UNINSTALLER_CTRL_START_Description {
            get {
                return ResourceManager.GetString("UNINSTALLER_CTRL_START_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string UNINSTALLER_CTRL_STOP_Description {
            get {
                return ResourceManager.GetString("UNINSTALLER_CTRL_STOP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove project from the registry (*).
        /// </summary>
        internal static string UNINSTALLER_FORCE_UNINSTALL {
            get {
                return ResourceManager.GetString("UNINSTALLER_FORCE_UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start CMD.EXE in install location.
        /// </summary>
        internal static string UNINSTALLER_START_CMD {
            get {
                return ResourceManager.GetString("UNINSTALLER_START_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start CMD.EXE in install location, with administrative privileges.
        /// </summary>
        internal static string UNINSTALLER_START_CMD_ADMIN {
            get {
                return ResourceManager.GetString("UNINSTALLER_START_CMD_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string WINDOW_C_Class {
            get {
                return ResourceManager.GetString("WINDOW_C_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Style.
        /// </summary>
        internal static string WINDOW_C_ExStyle {
            get {
                return ResourceManager.GetString("WINDOW_C_ExStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWND.
        /// </summary>
        internal static string WINDOW_C_HWND {
            get {
                return ResourceManager.GetString("WINDOW_C_HWND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string WINDOW_C_ID {
            get {
                return ResourceManager.GetString("WINDOW_C_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string WINDOW_C_Position {
            get {
                return ResourceManager.GetString("WINDOW_C_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        internal static string WINDOW_C_Process {
            get {
                return ResourceManager.GetString("WINDOW_C_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        internal static string WINDOW_C_ProcessID {
            get {
                return ResourceManager.GetString("WINDOW_C_ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string WINDOW_C_Size {
            get {
                return ResourceManager.GetString("WINDOW_C_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string WINDOW_C_Style {
            get {
                return ResourceManager.GetString("WINDOW_C_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread ID.
        /// </summary>
        internal static string WINDOW_C_ThreadID {
            get {
                return ResourceManager.GetString("WINDOW_C_ThreadID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string WINDOW_C_Title {
            get {
                return ResourceManager.GetString("WINDOW_C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize Window.
        /// </summary>
        internal static string WINDOWS_CTRL_CONTINUE_Description {
            get {
                return ResourceManager.GetString("WINDOWS_CTRL_CONTINUE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Window.
        /// </summary>
        internal static string WINDOWS_CTRL_PAUSE_Description {
            get {
                return ResourceManager.GetString("WINDOWS_CTRL_PAUSE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Window To Top.
        /// </summary>
        internal static string WINDOWS_CTRL_RESTART_Description {
            get {
                return ResourceManager.GetString("WINDOWS_CTRL_RESTART_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        internal static string WINDOWS_CTRL_START_Description {
            get {
                return ResourceManager.GetString("WINDOWS_CTRL_START_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window.
        /// </summary>
        internal static string WINDOWS_CTRL_STOP_Description {
            get {
                return ResourceManager.GetString("WINDOWS_CTRL_STOP_Description", resourceCulture);
            }
        }
    }
}
